language: java
# blocklist
branches:
  except:
  - development 

# safelist
branches:
  only:
  - stable
  - master
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
